name: Build and Test ROS 2 Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ROS 2 Package
    runs-on: ubuntu-22.04

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Or your desired Python version
        
    - name: Install Python Dependencies
      run: |
        python3 -m pip install --upgrade pip
        pip install catkin_pkg

    # Set up ROS 2
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.7
      with:
        required-ros-distributions: "humble" # Replace "humble" with your ROS 2 distribution

    # Install dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev

    # Install ROS dependencies
    - name: Install ROS dependencies
      run: |
        sudo apt update
        sudo apt install -y ros-humble-nav2-msgs

    # Setup workspace
    - name: Setup ROS 2 workspace
      run: |
        mkdir -p ~/ros2_ws/src
        ln -s ${{ github.workspace }} ~/ros2_ws/src/navigation_controler
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    # Build the workspace
    - name: Build workspace
      run: |
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        colcon build --cmake-args -DBUILD_TESTING=OFF

    # Test the package
    - name: Run tests
      run: |
        cd ~/ros2_ws
        source /opt/ros/humble/setup.bash
        colcon test
        colcon test-result --verbose
