name: Build and Test ROS 2 Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    name: Build ROS 2 Package
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        ros-distro: [humble]

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v3

    
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10' # Or your desired Python version

    # Set up ROS 2
    - name: Setup ROS 2
      uses: ros-tooling/setup-ros@v0.3
      with:
        required-ros-distributions: "humble" # Replace "humble" with your ROS 2 distribution

    # Install dependencies
    - name: Install system dependencies
      run: |
        sudo apt update
        sudo apt install -y libboost-all-dev

    # Install ROS dependencies
    - name: Install ROS dependencies
      run: |
        sudo apt update
        sudo apt install -y ros-${{ matrix.ros-distro }}-nav2-msgs

    # Setup workspace
    - name: Setup ROS 2 workspace
      run: |
        mkdir -p ~/ros2_ws/src
        ln -s ${{ github.workspace }} ~/ros2_ws/src/navigation_controler
        cd ~/ros2_ws
        rosdep init || true
        rosdep update
        rosdep install --from-paths src --ignore-src -r -y

    # Build the workspace
    - name: Build workspace
      run: |
        cd ~/ros2_ws
        colcon build

    # Test the package
    - name: Run tests
      run: |
        cd ~/ros2_ws
        colcon test
        colcon test-result --verbose
